version: '3.8'

services:
  backend:
    image: backend:latest
    build: ./backend  
    ports:
      - "8081:8081"   
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 20s
      retries: 5
      timeout: 15s
      start_period: 10s

  frontend:
    image: frontend:latest  
    build: ./frontend  
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 20s
      retries: 5
      timeout: 15s
      start_period: 10s

networks:
  app-network:
    driver: bridge 